ShopingWebSite/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopingWebSite.Models;

namespace ShopingWebSite.Controllers
{
    public class CategoryController : Controller
    {
        DatabaseContext context = new DatabaseContext();
        // GET: Category
        public PartialViewResult Menu()
        {
            IEnumerable<string> categories = context.Categories.Select(x => x.Name).Distinct();

            return PartialView("Menu",categories);
        }
    }
}

ShopingWebSite/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopingWebSite.Models;
using System.Web.Helpers;

namespace ShopingWebSite.Controllers
{
    public class PictureController : Controller
    {
        DatabaseContext context = new DatabaseContext();
        // GET: Picture
        public FileContentResult GetImage(int Id)
        {
            Picture picure = context.Pictures.FirstOrDefault(x => x.Id == Id);
            WebImage image = new WebImage(picure.ImageData);
            image.Resize(400, 300, false);
            if (picure != null)
            {
                return File(image.GetBytes(null), picure.ImageMimeType);
            }
            else return null;

        }
    }
}

ShopingWebSite/Views/Shared/ProductSummary.cshtml
@model ShopingWebSite.Models.ProductSummaryViewModel 


<div class="container-fluid">
    <div>
        <div class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                @{var firstpictre = Model.Pictures == null ? null : Model.Pictures.FirstOrDefault();}
                @foreach (var item in Model.Pictures)
                {
                    var cssclass = firstpictre != null ? firstpictre.Id == item.Id ? "carousel-item active" : "carousel-item" : "carousel-item";
                    <div class="@cssclass">
                        <img id="myimage" class="img-fluid shadow-lg p-0 bg-white rounded" src="@Url.Action("GetImage","Picture",new {Id = item.Id})" />
                    </div>
                }
            </div>
        </div>

    </div>
    <div>
        <h3>
            <strong>@Model.Product.Name</strong>
        </h3>
        <p><small>@Model.Product.Description</small></p>
    </div>
    <div class="row   shadow-lg p-0 mb-5 bg-white rounded border border-secondary d-block ">
        <div class="float-right">
            <label class="btn btn-default disabled">@Model.Product.Price</label>
        </div>
        <div class="float-left">
            @if (Model.Product.Quantity <= 0)
            {
                <label class="btn-info">@HttpContext.GetGlobalResourceObject("Labels", "RunOutOf")</label>
            }
            else
            {
                using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("Id", Model.Product.Id)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-default" value="@HttpContext.GetGlobalResourceObject("Labels","AddToCart")" />
                }
            }
        </div>
    </div>
</div>

ShopingWebSite/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-rtl.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(@HttpContext.GetGlobalResourceObject("Labels", "HeaderText") as string, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("محصولات", "ShowProducts", "Admin", new { @class = "navbar-text" })</li>
                    <li>@Html.ActionLink("دسته بندی ها", "Categories", "Admin", new { @class = "navbar-text" })</li>
                    <li>@Html.ActionLink("عکس ها", "Show", "Admin", new { @class = "navbar-text" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-xs-12">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShopingWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-rtl.css" rel="stylesheet" />
    <link href="~/Content/css/customestyle.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top d-block">
        <div class="container">
            @Html.ActionLink(@HttpContext.GetGlobalResourceObject("Labels", "HeaderText") as string, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="~/Home/Index">@HttpContext.GetGlobalResourceObject("Labels", "Home")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/About">@HttpContext.GetGlobalResourceObject("Labels", "About")</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/Contact">@HttpContext.GetGlobalResourceObject("Labels", "ContactUs")</a>
                    </li>
                    <li class="nav-item">@Html.Action("Summary", "Cart")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                @Html.Action("Menu", "Category")
            </div>
            <div class="col-xs-12 col-sm-9">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>